Reduce the logs
Near-One/btc-light-client-contract pull request #53
Opened 2024-08-08 11:21 UTC by olga24912

fix: https://github.com/Near-One/btc-light-client-contract/issues/46

2024-08-08 20:09 UTC, kiseln commented
What is the log limit?

2024-08-08 20:22 UTC, karim-en commented
> What is the log limit?

100

2024-08-09 08:09 UTC, kiseln approved these changes

2024-08-09 12:01 UTC, karim-en requested changes

2024-08-09 12:01 UTC, karim-en commented on contract/src/lib.rs
> +            block_hash: current_block_hash.clone(),
```suggestion
            block_hash: current_block_hash,
```

extra clone

2024-08-09 12:01 UTC, karim-en commented on contract/src/lib.rs
> +            log!("Block {}: saving to mainchain", current_block_hash);
```suggestion
            log!("Block {}: saving to mainchain", current_header.block_hash);
```

2024-08-09 12:01 UTC, karim-en commented on contract/src/lib.rs
> +            log!("Block {}: saving to fork", current_block_hash);
```suggestion
            log!("Block {}: saving to fork", current_header.block_hash);
```

2024-08-09 14:49 UTC, olga24912 commented on contract/src/lib.rs
> +            block_hash: current_block_hash.clone(),
fixed: https://github.com/Near-One/btc-light-client-contract/pull/53/commits/da81ff4eab50e113bcd7960b3f11238c539430fe

2024-08-09 14:49 UTC, olga24912 commented on contract/src/lib.rs
> +            log!("Block {}: saving to mainchain", current_block_hash);
fixed: https://github.com/Near-One/btc-light-client-contract/pull/53/commits/da81ff4eab50e113bcd7960b3f11238c539430fe

2024-08-09 14:49 UTC, olga24912 commented on contract/src/lib.rs
> +            log!("Block {}: saving to fork", current_block_hash);
fixed: https://github.com/Near-One/btc-light-client-contract/pull/53/commits/da81ff4eab50e113bcd7960b3f11238c539430fe

2024-08-09 18:00 UTC, merged